#!/usr/bin/env python3

import argparse
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate rain plots from a BrdU .bed file."
    )
    parser.add_argument(
        "input_file",
        help="Path to the BrdU .bed file generated by extract_brdu.py"
    )
    parser.add_argument(
        "-o", "--output_dir",
        required=False,
        default=None,
        help="Output directory for rain plots (default: output/rain_plot/)"
    )
    parser.add_argument(
        "--region_start",
        type=int,
        default=None,
        help="Start coordinate used for extraction (for output filename)"
    )
    parser.add_argument(
        "--region_end",
        type=int,
        default=None,
        help="End coordinate used for extraction (for output filename)"
    )
    parser.add_argument(
        "--rfb_dir",
        required=False,
        default=None,
        help="Path to the data/bed directory containing the RFB .bed file"
    )
    parser.add_argument(
        "--phase",
        required=False,
        default="Unknown",
        help="Phase label for the plot title (e.g., Mitosis or S Phase)"
    )
    parser.add_argument(
        "--output_manifest",
        required=False,
        default=None,
        help="Optional file to write the generated rain plot PNG paths to"
    )
    return parser.parse_args()


def load_rain_plot_input(input_file):
    """Converts the input .bed file into a pandas dataframe."""
    rain_plot_df = pd.read_csv(
        input_file,
        sep="\t",
        header=None,
        names=["chrom", "start", "end", "read_id", "mod_base", "mod_prob"],
    )
    return rain_plot_df


def get_output_dir(output_dir=None):
    """Determine the output directory for the rain plots."""
    if not output_dir:
        output_dir = os.path.join(os.getcwd(), "output", "rain_plot")
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


# Map GenBank IDs to chromosome numbers
genbank_to_chr = {
    "CM007964.1": "1",
    "CM007965.1": "2",
    "CM007966.1": "3",
    "CM007967.1": "4",
    "CM007968.1": "5",
    "CM007969.1": "6",
    "CM007970.1": "7",
    "CM007971.1": "8",
    "CM007972.1": "9",
    "CM007973.1": "10",
    "CM007974.1": "11",
    "CM007975.1": "12",
    "CM007976.1": "13",
    "CM007977.1": "14",
    "CM007978.1": "15",
    "CM007979.1": "16",
    "CM007980.1": "p2-micron",
    "CM007981.1": "MT"
}


def load_rfb_positions(rfb_dir, region_start, region_end):
    """
    Load RFB motif start positions per read from the RFB .bed file.
    Returns a dict of {read_id: [rfb_start_positions]}.
    """
    if not rfb_dir or region_start is None or region_end is None:
        return {}

    rfb_file = os.path.join(
        rfb_dir,
        f"rfb_bases{region_start}_to_{region_end}.bed"
    )

    if not os.path.exists(rfb_file):
        print(f"[WARN] RFB file not found: {rfb_file}", flush=True)
        return {}

    rfb_df = pd.read_csv(
        rfb_file,
        sep="\t",
        header=None,
        names=["chrom", "start", "end", "read_id", "mod_base", "mod_prob"]
    )

    # Build dict of read_id -> list of RFB start positions
    rfb_positions = {}
    for _, row in rfb_df.iterrows():
        rid = row["read_id"]
        if rid not in rfb_positions:
            rfb_positions[rid] = []
        rfb_positions[rid].append(int(row["start"]))

    print(
        f"[INFO] {len(rfb_positions)} reads with RFB motif positions loaded from {rfb_file}.",
        flush=True
    )
    return rfb_positions


# -------------------------------------------------------------------------
# OPTIONAL FILTER: Plot only reads that contain RFB coords
#
# This function filters the dataframe to only include reads that have been
# identified as containing the RFB motif sequence. This is useful when
# analysing S phase data where you only want to visualise reads that
# overlap with the replication fork barrier. To enable this filter:
#
# 1. Uncomment the function below
# 2. Uncomment the call to filter_reads_with_rfb() in
#    plot_rainplots_per_read() (marked below with UNCOMMENT TO ENABLE)
#
# When enabled, only reads present in the RFB .bed file will be plotted.
# Reads without RFB coords will be skipped entirely.
# -------------------------------------------------------------------------

# def filter_reads_with_rfb(df, rfb_positions):
#     """
#    Filter the dataframe to only include reads that contain RFB coords.
#     Returns a filtered dataframe containing only reads with RFB motif matches.
#     """
#     if not rfb_positions:
#         print("[WARN] No RFB positions loaded — skipping RFB filter.", flush=True)
#        return df

#     rfb_read_ids = set(rfb_positions.keys())
#     df_filtered = df[df["read_id"].isin(rfb_read_ids)]
#     print(f"[INFO] {df_filtered['read_id'].nunique()} reads remaining after RFB filter.", flush=True)
#     return df_filtered


def plot_rainplots_per_read(
    input_file,
    output_dir=None,
    region_start=None,
    region_end=None,
    rfb_dir=None,
    phase="Unknown",
    output_manifest=None
):
    df = load_rain_plot_input(input_file)
    outdir = get_output_dir(output_dir)

    df["start"] = pd.to_numeric(df["start"], errors="coerce", downcast="integer")
    df["mod_prob"] = pd.to_numeric(df["mod_prob"], errors="coerce", downcast="float")
    df = df.dropna(subset=["read_id", "start", "mod_prob"])

    max_reads = 100
    show_scatter = True
    threshold = 0.5

    df["mod_base"] = df["mod_base"].astype(str).str.upper()

    t_window = 100
    t_step = 45

    # Load RFB positions per read
    rfb_positions = load_rfb_positions(rfb_dir, region_start, region_end)

    # UNCOMMENT TO ENABLE: Filter to only plot reads that contain RFB coords
    # df = filter_reads_with_rfb(df, rfb_positions)

    # Get all unique reads with no filtering
    all_read_ids = df["read_id"].unique()
    if len(all_read_ids) == 0:
        raise ValueError("No reads found in the input file.")

    # Randomly sample up to max_reads
    sample_size = min(max_reads, len(all_read_ids))
    sampled_reads = np.random.choice(all_read_ids, size=sample_size, replace=False)
    df = df[df["read_id"].isin(sampled_reads)]

    generated_paths = []

    for i, (rid, sub) in enumerate(df.groupby("read_id", sort=False), start=1):
        if i > max_reads:
            break

        sub = sub.sort_values("start", kind="mergesort")

        genbank_ids = sub["chrom"].astype(str).unique()
        if len(genbank_ids) == 1:
            chr_label = genbank_to_chr.get(genbank_ids[0], genbank_ids[0])
        else:
            chr_label = "mixed/" + ",".join(
                genbank_to_chr.get(g, g) for g in genbank_ids
            )

        read_start = sub["start"].min()
        x = (sub["start"].to_numpy() - read_start) / 1000.0
        y = sub["mod_prob"].to_numpy(dtype=float)
        bases = sub["mod_base"].to_numpy(dtype=object)

        if len(x) < 2:
            continue

        t_idx = np.flatnonzero(bases == "T")
        if t_idx.size < t_window:
            continue

        # Threshold: convert probabilities to binary (1 if >= threshold, else 0)
        y_binary = (y >= threshold).astype(float)

        edges = []
        y_vals = []

        for j in range(0, t_idx.size - t_window + 1, t_step):
            window_t_idx = t_idx[j:j + t_window]
            if len(window_t_idx) < t_window:
                continue

            left_i = int(window_t_idx[0])
            right_i = int(window_t_idx[-1])

            x_left = float(x[left_i])
            x_right = float(x[right_i])

            if x_right < x_left:
                continue

            if not edges:
                edges.append(x_left)
            edges.append(x_right)

            # Mean of binary values = fraction of T's called as BrdU in this window
            y_bin = float(np.mean(y_binary[window_t_idx]))
            y_vals.append(y_bin)

        edges = np.asarray(edges, dtype=float)
        y_vals = np.asarray(y_vals, dtype=float)

        if len(edges) < 2 or len(y_vals) < 1:
            continue

        edges = np.maximum.accumulate(edges)

        if len(edges) >= 2 and edges[-1] == edges[-2]:
            edges[-1] = edges[-1] + 1e-9

        if len(edges) != len(y_vals) + 1:
            continue

        fig, ax = plt.subplots(figsize=(16, 4))

        # Scatter uses raw probabilities
        if show_scatter:
            ax.scatter(x, y, s=1, color="black", alpha=0.3)

        # Staircase uses binary thresholded mean (fraction of BrdU per window)
        ax.stairs(y_vals, edges, linewidth=2, color="black", fill=False)

        # Draw red vertical line at each RFB motif start position for this read
        if rid in rfb_positions:
            for rfb_start in rfb_positions[rid]:
                rfb_x = (rfb_start - read_start) / 1000.0
                ax.axvline(
                    x=rfb_x,
                    color="red",
                    linewidth=1.5,
                    linestyle="--",
                    label="RFB"
                )

            # Only show one legend entry even if multiple RFB lines
            handles, labels = ax.get_legend_handles_labels()
            ax.legend([handles[0]], [labels[0]], loc="upper right")

        ax.set_ylim(0, 1)
        ax.set_xlabel("Position within read (kb)")
        ax.set_ylabel("BrdU incorporation rate (0–1)")
        ax.set_title(f"{phase} Rain Plot {rid} - Read {i}\nChromosome: {chr_label}")

        outpath = os.path.join(
            outdir,
            f"rainplot_chr{chr_label}_{region_start}_{region_end}_{i:03d}.png"
        )

        fig.tight_layout()
        fig.savefig(outpath, dpi=200)
        plt.close(fig)
        generated_paths.append(outpath)

    if output_manifest:
        with open(output_manifest, "w", encoding="utf-8") as handle:
            for path in generated_paths:
                handle.write(f"{path}\n")


if __name__ == "__main__":
    args = parse_args()
    plot_rainplots_per_read(
        args.input_file,
        args.output_dir,
        args.region_start,
        args.region_end,
        args.rfb_dir,
        args.phase,
        args.output_manifest
    )
