#!/usr/bin/env python3

import argparse
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate rain plots from a BrdU .bed file."
    )
    parser.add_argument(
        "input_file",
        help="Path to the BrdU .bed file generated by extract_brdu.py"
    )
    parser.add_argument(
        "-o", "--output_dir",
        required=False,
        default=None,
        help="Output directory for rain plots (default: output/rain_plot/)"
    )
    parser.add_argument(
        "--region_start",
        type=int,
        default=None,
        help="Start coordinate used for extraction (for output filename)"
    )
    parser.add_argument(
        "--region_end",
        type=int,
        default=None,
        help="End coordinate used for extraction (for output filename)"
    )
    parser.add_argument(
        "--rfb_dir",
        required=False,
        default=None,
        help="Path to the data/bed directory containing the RFB .bed file"
    )
    parser.add_argument(
        "--phase",
        required=False,
        default="Unknown",
        help="Phase label for the plot title (e.g., Mitosis or S Phase)"
    )
    parser.add_argument(
        "--output_manifest",
        required=False,
        default=None,
        help="Optional file to write the generated rain plot PNG paths to"
    )
    parser.add_argument(
        "--filename_prefix",
        required=False,
        default=None,
        help="Optional prefix to use in generated rain plot PNG filenames"
    )
    parser.add_argument(
        "--filter_reads_with_rfb",
        action="store_true",
        help="Plot only reads that have matching RFB coordinates"
    )
    parser.add_argument(
        "--show_rfb_overlay",
        action="store_true",
        help="Draw RFB coordinate markers on the rain plots"
    )
    parser.add_argument(
        "--brdu_window_mode",
        choices=["binary", "mean"],
        default="binary",
        help=(
            "How to summarize BrdU probabilities in each T window. "
            "binary thresholds probabilities before averaging; mean averages "
            "raw probabilities directly."
        )
    )
    parser.add_argument(
        "--binary_threshold",
        type=float,
        default=0.5,
        help="Probability threshold used by binary T-window mode. Defaults to 0.5."
    )
    parser.add_argument(
        "--max_reads",
        type=int,
        default=None,
        help="Maximum number of reads to plot. Defaults to all reads in the region."
    )
    parser.add_argument(
        "--preserve_read_order_for_max_reads",
        action="store_true",
        help=(
            "When --max_reads is set, keep the first N reads from input order "
            "instead of randomly sampling."
        )
    )
    return parser.parse_args()


def load_rain_plot_input(input_file):
    """Converts the input .bed file into a pandas dataframe."""
    rain_plot_df = pd.read_csv(
        input_file,
        sep="\t",
        header=None,
        names=["chrom", "start", "end", "read_id", "mod_base", "mod_prob"],
    )
    return rain_plot_df


def get_output_dir(output_dir=None):
    """Determine the output directory for the rain plots."""
    if not output_dir:
        output_dir = os.path.join(os.getcwd(), "output", "rain_plot")
    os.makedirs(output_dir, exist_ok=True)
    return output_dir


def get_region_metadata_path(output_dir):
    """Path for per-rainplot genomic window metadata."""
    return os.path.join(output_dir, "rainplot_regions.tsv")


# Map GenBank IDs to chromosome numbers
genbank_to_chr = {
    "CM007964.1": "1",
    "CM007965.1": "2",
    "CM007966.1": "3",
    "CM007967.1": "4",
    "CM007968.1": "5",
    "CM007969.1": "6",
    "CM007970.1": "7",
    "CM007971.1": "8",
    "CM007972.1": "9",
    "CM007973.1": "10",
    "CM007974.1": "11",
    "CM007975.1": "12",
    "CM007976.1": "13",
    "CM007977.1": "14",
    "CM007978.1": "15",
    "CM007979.1": "16",
    "CM007980.1": "p2-micron",
    "CM007981.1": "MT"
}

M_PHASE_CHROMOSOME_IDS = {
    "CM007964.1",
    "CM007965.1",
    "CM007966.1",
    "CM007967.1",
    "CM007968.1",
    "CM007969.1",
    "CM007970.1",
    "CM007971.1",
    "CM007972.1",
    "CM007973.1",
    "CM007974.1",
    "CM007975.1",
    "CM007976.1",
    "CM007977.1",
    "CM007978.1",
    "CM007979.1",
}

M_PHASE_EXCLUDED_REFERENCE_IDS = {
    "LYZE01000019.1",
    "LYZE01000020.1",
    "LYZE01000021.1",
    "CM007980.1",
    "CM007981.1",
}


def is_m_phase(phase):
    """Return True when the phase label refers to M phase/mitosis."""
    return str(phase).strip().lower() in {"m", "m phase", "m-phase", "mphase", "mitosis"}


def is_allowed_m_phase_reference(genbank_ids):
    """M phase rainplots should only use reads aligned to chromosomes 1-16."""
    reference_ids = {str(genbank_id) for genbank_id in genbank_ids}
    if reference_ids & M_PHASE_EXCLUDED_REFERENCE_IDS:
        return False
    return reference_ids.issubset(M_PHASE_CHROMOSOME_IDS)


def load_rfb_positions(rfb_dir, region_start, region_end):
    """
    Load RFB motif start positions per read from the RFB .bed file.
    Returns a dict of {read_id: [rfb_start_positions]}.
    """
    if not rfb_dir or region_start is None or region_end is None:
        return {}

    rfb_file = os.path.join(
        rfb_dir,
        f"rfb_bases{region_start}_to_{region_end}.bed"
    )

    if not os.path.exists(rfb_file):
        print(f"[WARN] RFB file not found: {rfb_file}", flush=True)
        return {}

    rfb_df = pd.read_csv(
        rfb_file,
        sep="\t",
        header=None,
        names=["chrom", "start", "end", "read_id", "mod_base", "mod_prob"]
    )

    # Build dict of read_id -> list of RFB start positions
    rfb_positions = {}
    for _, row in rfb_df.iterrows():
        rid = row["read_id"]
        if rid not in rfb_positions:
            rfb_positions[rid] = []
        rfb_positions[rid].append(int(row["start"]))

    print(
        f"[INFO] {len(rfb_positions)} reads with RFB motif positions loaded from {rfb_file}.",
        flush=True
    )
    return rfb_positions


def filter_reads_with_rfb(df, rfb_positions):
    """
    Filter the dataframe to only include reads that contain RFB coords.
    Returns a filtered dataframe containing only reads with RFB motif matches.
    """
    if not rfb_positions:
        print("[WARN] No RFB positions loaded; skipping RFB-only read filter.", flush=True)
        return df

    rfb_read_ids = set(rfb_positions.keys())
    df_filtered = df[df["read_id"].isin(rfb_read_ids)]
    print(
        f"[INFO] {df_filtered['read_id'].nunique()} reads remaining after RFB filter.",
        flush=True
    )
    return df_filtered


def plot_rainplots_per_read(
    input_file,
    output_dir=None,
    region_start=None,
    region_end=None,
    rfb_dir=None,
    phase="Unknown",
    output_manifest=None,
    filename_prefix=None,
    filter_reads_with_rfb_only=False,
    show_rfb_overlay=False,
    brdu_window_mode="binary",
    binary_threshold=0.5,
    max_reads=None,
    preserve_read_order_for_max_reads=False,
):
    if not 0 <= binary_threshold <= 1:
        raise ValueError("binary_threshold must be between 0 and 1.")
    if max_reads is not None and max_reads < 1:
        raise ValueError("max_reads must be at least 1 when provided.")

    df = load_rain_plot_input(input_file)
    outdir = get_output_dir(output_dir)

    df["start"] = pd.to_numeric(df["start"], errors="coerce", downcast="integer")
    df["mod_prob"] = pd.to_numeric(df["mod_prob"], errors="coerce", downcast="float")
    df = df.dropna(subset=["read_id", "start", "mod_prob"])

    show_scatter = True
    threshold = binary_threshold

    df["mod_base"] = df["mod_base"].astype(str).str.upper()

    t_window = 100
    t_step = 45

    # Load RFB positions per read
    rfb_positions = load_rfb_positions(rfb_dir, region_start, region_end)

    if filter_reads_with_rfb_only:
        df = filter_reads_with_rfb(df, rfb_positions)

    m_phase_only_chromosomes = is_m_phase(phase)

    # Get all unique reads with no filtering
    all_read_ids = df["read_id"].unique()
    if len(all_read_ids) == 0:
        raise ValueError("No reads found in the input file.")

    if max_reads is not None:
        if not preserve_read_order_for_max_reads:
            sample_size = min(max_reads, len(all_read_ids))
            selected_reads = np.random.choice(
                all_read_ids,
                size=sample_size,
                replace=False
            )
            df = df[df["read_id"].isin(selected_reads)]

    generated_paths = []
    region_records = []
    skipped_m_phase_reference_reads = 0
    skipped_unplottable_reads = 0

    for rid, sub in df.groupby("read_id", sort=False):
        sub = sub.sort_values("start", kind="mergesort")

        genbank_ids = sub["chrom"].astype(str).unique()
        if m_phase_only_chromosomes and not is_allowed_m_phase_reference(genbank_ids):
            skipped_m_phase_reference_reads += 1
            continue

        if len(genbank_ids) == 1:
            chr_label = genbank_to_chr.get(genbank_ids[0], genbank_ids[0])
        else:
            chr_label = "mixed/" + ",".join(
                genbank_to_chr.get(g, g) for g in genbank_ids
            )

        read_start = int(sub["start"].min())
        if "end" in sub.columns:
            sub["end"] = pd.to_numeric(sub["end"], errors="coerce", downcast="integer")
        read_end = int(sub["end"].dropna().max()) if sub["end"].notna().any() else int(sub["start"].max())
        if read_end <= read_start:
            read_end = read_start + 1

        x = sub["start"].to_numpy(dtype=float) / 1000.0
        y = sub["mod_prob"].to_numpy(dtype=float)
        bases = sub["mod_base"].to_numpy(dtype=object)

        if len(x) < 2:
            skipped_unplottable_reads += 1
            continue

        t_idx = np.flatnonzero(bases == "T")
        if t_idx.size < t_window:
            skipped_unplottable_reads += 1
            continue

        # Threshold: convert probabilities to binary (1 if >= threshold, else 0)
        y_binary = (y >= threshold).astype(float)

        edges = []
        y_vals = []

        for j in range(0, t_idx.size - t_window + 1, t_step):
            window_t_idx = t_idx[j:j + t_window]
            if len(window_t_idx) < t_window:
                continue

            left_i = int(window_t_idx[0])
            right_i = int(window_t_idx[-1])

            x_left = float(x[left_i])
            x_right = float(x[right_i])

            if x_right < x_left:
                continue

            if not edges:
                edges.append(x_left)
            edges.append(x_right)

            if brdu_window_mode == "mean":
                # Mean mode averages raw BrdU probabilities over the T window.
                y_window = float(np.mean(y[window_t_idx]))
            else:
                # Binary mode keeps the original behavior: threshold first,
                # then average to get the fraction of T's called as BrdU.
                y_window = float(np.mean(y_binary[window_t_idx]))
            y_vals.append(y_window)

        edges = np.asarray(edges, dtype=float)
        y_vals = np.asarray(y_vals, dtype=float)

        if len(edges) < 2 or len(y_vals) < 1:
            skipped_unplottable_reads += 1
            continue

        edges = np.maximum.accumulate(edges)

        if len(edges) >= 2 and edges[-1] == edges[-2]:
            edges[-1] = edges[-1] + 1e-9

        if len(edges) != len(y_vals) + 1:
            skipped_unplottable_reads += 1
            continue

        fig, ax = plt.subplots(figsize=(16, 4))
        read_number = len(generated_paths) + 1

        # Scatter uses raw probabilities
        if show_scatter:
            ax.scatter(x, y, s=1, color="black", alpha=0.3)

        # Staircase uses the selected T-window aggregation mode.
        ax.stairs(y_vals, edges, linewidth=2, color="black", fill=False)

        # Draw red vertical line at each RFB motif start position for this read
        if show_rfb_overlay and rid in rfb_positions:
            for rfb_start in rfb_positions[rid]:
                rfb_x = rfb_start / 1000.0
                ax.axvline(
                    x=rfb_x,
                    color="red",
                    linewidth=1.5,
                    linestyle="--",
                    label="RFB"
                )

            # Only show one legend entry even if multiple RFB lines
            handles, labels = ax.get_legend_handles_labels()
            ax.legend([handles[0]], [labels[0]], loc="upper right")

        ax.set_ylim(0, 1)
        ax.set_xlim(read_start / 1000.0, read_end / 1000.0)
        ax.set_xlabel("Genomic position (kb)")
        if brdu_window_mode == "mean":
            y_label = "Mean BrdU probability (0-1)"
            mode_label = "mean probability"
        else:
            y_label = "BrdU incorporation rate (0-1)"
            mode_label = f"binary threshold >= {threshold:g}"

        ax.set_ylabel(y_label)
        ax.set_title(
            f"{phase} Rain Plot {rid} - Read {read_number}\n"
            f"Chromosome: {chr_label} | Window: {read_start}-{read_end} bp | "
            f"T-window mode: {mode_label}"
        )

        if filename_prefix:
            output_name = f"rainplot_{filename_prefix}_{read_number:03d}.png"
        else:
            output_name = f"rainplot_chr{chr_label}_{region_start}_{region_end}_{read_number:03d}.png"

        outpath = os.path.join(outdir, output_name)

        fig.tight_layout()
        fig.savefig(outpath, dpi=200)
        plt.close(fig)
        generated_paths.append(outpath)
        region_records.append(
            {
                "rainplot_path": outpath,
                "chrom": genbank_ids[0] if len(genbank_ids) == 1 else str(genbank_ids[0]),
                "read_start": read_start,
                "read_end": read_end,
            }
        )

        if max_reads is not None and preserve_read_order_for_max_reads and len(generated_paths) >= max_reads:
            break

    if skipped_m_phase_reference_reads:
        print(
            "[INFO] "
            f"Skipped {skipped_m_phase_reference_reads} M-phase reads aligned outside chromosomes 1-16.",
            flush=True,
        )

    if skipped_unplottable_reads:
        print(
            "[INFO] "
            f"Skipped {skipped_unplottable_reads} reads that did not have enough BrdU/T-window data to plot.",
            flush=True,
        )

    if max_reads is not None and len(generated_paths) < max_reads:
        print(
            "[WARN] "
            f"Requested {max_reads} rainplots, but only {len(generated_paths)} plottable reads were available.",
            flush=True,
        )

    if output_manifest:
        with open(output_manifest, "w", encoding="utf-8") as handle:
            for path in generated_paths:
                handle.write(f"{path}\n")

    if region_records:
        metadata_path = get_region_metadata_path(outdir)
        region_df = pd.DataFrame(region_records)

        if os.path.exists(metadata_path):
            existing_region_df = pd.read_csv(metadata_path, sep="\t")
            region_df = pd.concat(
                [existing_region_df, region_df],
                ignore_index=True
            ).drop_duplicates(subset=["rainplot_path"], keep="last")

        region_df.to_csv(
            metadata_path,
            sep="\t",
            index=False
        )


if __name__ == "__main__":
    args = parse_args()
    plot_rainplots_per_read(
        args.input_file,
        args.output_dir,
        args.region_start,
        args.region_end,
        args.rfb_dir,
        args.phase,
        args.output_manifest,
        args.filename_prefix,
        args.filter_reads_with_rfb,
        args.show_rfb_overlay,
        args.brdu_window_mode,
        args.binary_threshold,
        args.max_reads,
        args.preserve_read_order_for_max_reads,
    )
