#!/bin/bash

# ==============================================================================
# POI VENN DIAGRAM, MEMBERSHIP, AND SUMMARY WORKFLOW
# ==============================================================================
#
# Purpose
# -------
# This SLURM workflow combines two original point-of-interest (POI) CSV files
# with the overlap CSV generated by the POI-comparison workflow. It validates
# that every reported overlap maps back to the selected source files, computes
# the three Venn regions, writes detailed membership and summary CSV files, and
# generates a publication-ready Venn-style PNG.
#
# Run from the workflow root:
#
#   cd /beevol/home/pineirok/workflows
#   bash src/utils/create_poi_venn.sh
#
# Interactive stage
# -----------------
# The launcher:
#
#   1. Lists CSV files under data/csv.
#   2. Prompts for the first original POI CSV.
#   3. Prompts for the second original POI CSV.
#   4. Prompts for the overlap CSV created from those two source files.
#   5. Prevents identical source selections.
#   6. Constructs output names from the source prefixes.
#   7. Submits this same script to SLURM in --run-analysis mode.
#
# Analysis stage
# --------------
# The submitted job:
#
#   1. Creates or reuses the project Python virtual environment.
#   2. Installs NumPy, pandas, and Matplotlib when missing.
#   3. Validates the original POI CSV schemas.
#   4. Validates the overlap CSV schema.
#   5. Maps each overlap pair back to an exact source coordinate.
#   6. Confirms that the overlap CSV belongs to the selected source files.
#   7. Calculates unique-to-first, overlap, and unique-to-second counts.
#   8. Builds a combined membership CSV containing every Venn region.
#   9. Builds a one-row summary CSV with counts and overlap percentages.
#  10. Creates a clean two-circle Venn-style PNG.
#
# Required source CSV columns
# ---------------------------
# Each original POI CSV must contain:
#
#   chrom
#   start
#   end
#
# Optional source columns such as rank, position, BrdU_pct, frac_mod, Nmod,
# combined_Nmod, and coverage values are preserved when possible.
#
# Required overlap CSV columns
# ----------------------------
# The overlap CSV must contain:
#
#   chrom
#   first_start
#   first_end
#   first_position
#   second_start
#   second_end
#   second_position
#   distance_bp
#
# The overlap rows are mapped back to the source files using exact:
#
#   chromosome, start, end
#
# coordinates. This prevents a Venn diagram from being generated from an
# overlap file that belongs to different source CSVs.
#
# Venn region definitions
# -----------------------
# unique_to_first:
#   Valid POIs in the first source CSV that are not represented by an overlap
#   pair.
#
# overlap:
#   One-to-one overlap pairs listed in the overlap CSV.
#
# unique_to_second:
#   Valid POIs in the second source CSV that are not represented by an overlap
#   pair.
#
# Consistency checks
# ------------------
# The workflow requires:
#
#   unique_to_first + overlap == first_total
#   unique_to_second + overlap == second_total
#
# It stops with an error when these relationships do not hold.
#
# Outputs
# -------
# Venn PNG:
#
#   results/venn_diagram/
#   <first_prefix>.<second_prefix>.venn_diagram.png
#
# Membership CSV:
#
#   data/csv/
#   <first_prefix>.<second_prefix>.venn_membership.csv
#
# Summary CSV:
#
#   data/csv/
#   <first_prefix>.<second_prefix>.venn_summary.csv
#
# Combined SLURM log:
#
#   data/csv/
#   <first_prefix>.<second_prefix>.venn.log
#
# Python environment
# ------------------
# The workflow creates or reuses:
#
#   /beevol/home/pineirok/workflows/.venv
#
# Required packages:
#
#   numpy
#   pandas
#   matplotlib
#
# ==============================================================================

#
# Save as:
#   /beevol/home/pineirok/workflows/src/utils/create_poi_venn.sh
#
# Run from the workflow root:
#   cd /beevol/home/pineirok/workflows
#   bash src/utils/create_poi_venn.sh
#

#SBATCH --job-name=poi_venn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=01:00:00

set -euo pipefail


# =============================================================================
# Project paths
# =============================================================================

# Root of the workflow project.
PROJECT_DIR="/beevol/home/pineirok/workflows"

# Input CSV files, generated CSV files, and SLURM logs.
CSV_DIR="${PROJECT_DIR}/data/csv"

# Generated Venn diagram PNG files.
VENN_DIR="${PROJECT_DIR}/results/venn_diagram"

# Reusable Python virtual environment.
VENV_DIR="${PROJECT_DIR}/.venv"

# Create required output directories.
mkdir -p "${CSV_DIR}" "${VENN_DIR}"


# =============================================================================
# Helper functions
# =============================================================================


# ==============================================================================
# FUNCTION: list_csv_files
# ==============================================================================
#
# Purpose:
#   List CSV files directly under CSV_DIR.
#
# Behavior:
#   - Does not recurse into subdirectories.
#   - Matches .csv case-insensitively.
#   - Prints filenames without directory paths.
#   - Sorts filenames alphabetically.
#
list_csv_files() {
    find "${CSV_DIR}" \
        -maxdepth 1 \
        -type f \
        -iname "*.csv" \
        -printf "%f\n" |
        sort
}


# ==============================================================================
# FUNCTION: resolve_selected_file
# ==============================================================================
#
# Purpose:
#   Resolve a numeric menu selection, full path, or filename under CSV_DIR.
#
# Arguments:
#   $1
#       User selection.
#
#   $2
#       Name of the Bash array containing available CSV filenames.
#
# Resolution order:
#   1. Numeric input is interpreted as a one-based menu selection.
#   2. An existing full or relative path is accepted.
#   3. A filename under CSV_DIR is accepted.
#
# Output:
#   Resolved CSV path.
#
# Return status:
#   0 when the file is resolved.
#   1 when the selection is invalid.
#
resolve_selected_file() {
    local selection="$1"
    local array_name="$2"

    # Create a nameref to the supplied array.
    local -n files_ref="${array_name}"

    # Allow selection by list number.
    if [[ "${selection}" =~ ^[0-9]+$ ]]; then
        local index=$((selection - 1))

        if (( index < 0 || index >= ${#files_ref[@]} )); then
            echo "[ERROR] Selection ${selection} is outside the available range." >&2
            return 1
        fi

        printf "%s\n" "${CSV_DIR}/${files_ref[index]}"
        return 0
    fi

    # Allow a complete path.
    if [[ -f "${selection}" ]]; then
        realpath "${selection}"
        return 0
    fi

    # Allow a filename located under data/csv.
    if [[ -f "${CSV_DIR}/${selection}" ]]; then
        realpath "${CSV_DIR}/${selection}"
        return 0
    fi

    echo "[ERROR] CSV file not found: ${selection}" >&2
    return 1
}


# ==============================================================================
# FUNCTION: remove_csv_extension
# ==============================================================================
#
# Purpose:
#   Remove the path and .csv extension from a CSV filename.
#
# Supported extensions:
#   .csv
#   .CSV
#
remove_csv_extension() {
    local filename

    filename="$(basename "$1")"
    filename="${filename%.csv}"
    filename="${filename%.CSV}"

    printf "%s\n" "${filename}"
}


# =============================================================================
# Python virtual environment
# =============================================================================


# ==============================================================================
# FUNCTION: prepare_python_environment
# ==============================================================================
#
# Purpose:
#   Create or reuse the project Python virtual environment and ensure all
#   required packages are installed.
#
# Required packages:
#   numpy
#   pandas
#   matplotlib
#
# Steps:
#   1. Attempt to load an available Python or Anaconda module.
#   2. Locate python3 or python.
#   3. Create VENV_DIR when missing.
#   4. Activate the virtual environment.
#   5. Install pip when necessary.
#   6. Install only missing dependencies.
#   7. Validate imports and print package versions.
#
# Global variables assigned:
#   SYSTEM_PYTHON
#       System Python executable used to create the environment.
#
#   PYTHON_CMD
#       Active Python executable inside VENV_DIR.
#
prepare_python_environment() {
    echo
    echo "============================================================"
    echo "Preparing Python environment"
    echo "============================================================"

    # Try to load a Python module.
    if command -v module >/dev/null 2>&1; then
        module purge >/dev/null 2>&1 || true

        if module load anaconda3 >/dev/null 2>&1; then
            echo "[INFO] Loaded module: anaconda3"
        elif module load python >/dev/null 2>&1; then
            echo "[INFO] Loaded module: python"
        elif module load Python >/dev/null 2>&1; then
            echo "[INFO] Loaded module: Python"
        else
            echo "[WARNING] No Python module could be loaded."
            echo "[WARNING] Using the Python installation already available."
        fi
    else
        echo "[WARNING] The module command is unavailable."
        echo "[WARNING] Using the Python installation already available."
    fi

    # Locate Python.
    if command -v python3 >/dev/null 2>&1; then
        SYSTEM_PYTHON="$(command -v python3)"
    elif command -v python >/dev/null 2>&1; then
        SYSTEM_PYTHON="$(command -v python)"
    else
        echo "[ERROR] Python could not be found." >&2
        exit 1
    fi

    echo "[INFO] System Python: ${SYSTEM_PYTHON}"

    # Create the virtual environment only if it does not exist.
    if [[ ! -f "${VENV_DIR}/bin/activate" ]]; then
        echo "[INFO] Virtual environment does not exist."
        echo "[INFO] Creating:"
        echo "       ${VENV_DIR}"

        "${SYSTEM_PYTHON}" -m venv "${VENV_DIR}"
    else
        echo "[INFO] Existing virtual environment found:"
        echo "       ${VENV_DIR}"
    fi

    # Activate the existing or newly created environment.
    # shellcheck disable=SC1091
    source "${VENV_DIR}/bin/activate"

    echo "[INFO] Activated virtual environment."
    echo "[INFO] Active Python: $(command -v python)"

    # Make sure pip is available.
    if ! python -m pip --version >/dev/null 2>&1; then
        echo "[INFO] pip is missing. Installing pip..."
        python -m ensurepip --upgrade
    fi

    # Install only missing packages.
    MISSING_PACKAGES=()

    if ! python -c "import numpy" >/dev/null 2>&1; then
        MISSING_PACKAGES+=("numpy")
    fi

    if ! python -c "import pandas" >/dev/null 2>&1; then
        MISSING_PACKAGES+=("pandas")
    fi

    if ! python -c "import matplotlib" >/dev/null 2>&1; then
        MISSING_PACKAGES+=("matplotlib")
    fi

    if (( ${#MISSING_PACKAGES[@]} > 0 )); then
        echo "[INFO] Installing missing packages:"
        printf "       %s\n" "${MISSING_PACKAGES[@]}"

        python -m pip install "${MISSING_PACKAGES[@]}"
    else
        echo "[INFO] Required packages are already installed."
        echo "[INFO] No package installation is needed."
    fi

    # Validate the environment.
    python - <<'PYTHON_CHECK'
import matplotlib
import numpy
import pandas

print("[INFO] Python package validation passed.")
print(f"[INFO] NumPy version:      {numpy.__version__}")
print(f"[INFO] pandas version:     {pandas.__version__}")
print(f"[INFO] matplotlib version: {matplotlib.__version__}")
PYTHON_CHECK

    PYTHON_CMD="$(command -v python)"

    echo "============================================================"
}


# =============================================================================
# Interactive prompts and SLURM submission
# =============================================================================


# ==============================================================================
# FUNCTION: submit_interactive_job
# ==============================================================================
#
# Purpose:
#   Run the interactive CSV-selection stage and submit the Venn analysis to
#   SLURM.
#
# This function:
#   - Requires at least three CSV files.
#   - Lists available files.
#   - Prompts for two source POI CSVs.
#   - Prompts for the overlap CSV.
#   - Prevents invalid duplicate selections.
#   - Constructs all output paths.
#   - Displays the final job configuration.
#   - Submits this same script using --run-analysis.
#
submit_interactive_job() {
    if [[ ! -d "${CSV_DIR}" ]]; then
        echo "[ERROR] CSV directory does not exist:" >&2
        echo "        ${CSV_DIR}" >&2
        exit 1
    fi

    # Read available CSV filenames into an indexed Bash array.
    mapfile -t CSV_FILES < <(list_csv_files)

    if (( ${#CSV_FILES[@]} < 3 )); then
        echo "[ERROR] At least three CSV files are required under:" >&2
        echo "        ${CSV_DIR}" >&2
        exit 1
    fi

    echo
    echo "============================================================"
    echo "Available CSV files"
    echo "Directory: ${CSV_DIR}"
    echo "============================================================"

    local i

    # Display a one-based numbered file menu.
    for i in "${!CSV_FILES[@]}"; do
        printf "  %3d) %s\n" \
            "$((i + 1))" \
            "${CSV_FILES[i]}"
    done

    # --------------------------------------------------------------------------
    # Select the first original POI CSV
    # --------------------------------------------------------------------------

    echo
    read -r -p \
        "Enter the number or filename for the FIRST original POI CSV: " \
        FIRST_SELECTION

    FIRST_CSV="$(
        resolve_selected_file \
            "${FIRST_SELECTION}" \
            CSV_FILES
    )"

    # --------------------------------------------------------------------------
    # Select the second original POI CSV
    # --------------------------------------------------------------------------

    echo
    read -r -p \
        "Enter the number or filename for the SECOND original POI CSV: " \
        SECOND_SELECTION

    SECOND_CSV="$(
        resolve_selected_file \
            "${SECOND_SELECTION}" \
            CSV_FILES
    )"

    # --------------------------------------------------------------------------
    # Select the overlap CSV
    # --------------------------------------------------------------------------

    echo
    read -r -p \
        "Enter the number or filename for the OVERLAP CSV: " \
        OVERLAP_SELECTION

    OVERLAP_CSV="$(
        resolve_selected_file \
            "${OVERLAP_SELECTION}" \
            CSV_FILES
    )"

    # Prevent identical source datasets.
    if [[ "${FIRST_CSV}" == "${SECOND_CSV}" ]]; then
        echo "[ERROR] The first and second POI CSV files are identical." >&2
        exit 1
    fi

    # The overlap CSV must be different from both source files.
    if [[ "${FIRST_CSV}" == "${OVERLAP_CSV}" ||
          "${SECOND_CSV}" == "${OVERLAP_CSV}" ]]; then

        echo "[ERROR] The overlap CSV must differ from both source CSVs." >&2
        exit 1
    fi

    # Construct output prefixes from the source CSV filenames.
    FIRST_PREFIX="$(remove_csv_extension "${FIRST_CSV}")"
    SECOND_PREFIX="$(remove_csv_extension "${SECOND_CSV}")"

    OUTPUT_PREFIX="${FIRST_PREFIX}.${SECOND_PREFIX}"

    # PNG goes under results/venn_diagram.
    OUTPUT_PNG="${VENN_DIR}/${OUTPUT_PREFIX}.venn_diagram.png"

    # CSV and log outputs stay under data/csv.
    OUTPUT_MEMBERSHIP="${CSV_DIR}/${OUTPUT_PREFIX}.venn_membership.csv"
    OUTPUT_SUMMARY="${CSV_DIR}/${OUTPUT_PREFIX}.venn_summary.csv"
    LOG_FILE="${CSV_DIR}/${OUTPUT_PREFIX}.venn.log"

    # Display the complete job configuration.
    echo
    echo "============================================================"
    echo "POI Venn diagram job"
    echo "============================================================"
    echo "First POI CSV:"
    echo "  ${FIRST_CSV}"
    echo
    echo "Second POI CSV:"
    echo "  ${SECOND_CSV}"
    echo
    echo "Overlap CSV:"
    echo "  ${OVERLAP_CSV}"
    echo
    echo "Venn PNG:"
    echo "  ${OUTPUT_PNG}"
    echo
    echo "Combined membership CSV:"
    echo "  ${OUTPUT_MEMBERSHIP}"
    echo
    echo "Summary CSV:"
    echo "  ${OUTPUT_SUMMARY}"
    echo
    echo "SLURM log:"
    echo "  ${LOG_FILE}"
    echo
    echo "Resources: 4 CPUs, 8 GB RAM, 1 hour"
    echo "============================================================"
    echo

    # Confirm SLURM submission is available.
    if ! command -v sbatch >/dev/null 2>&1; then
        echo "[ERROR] The sbatch command is unavailable." >&2
        echo "[ERROR] Run this script on an HPC node with SLURM access." >&2
        exit 1
    fi

    # Submit this same script in internal analysis mode.
    #
    # Standard output and standard error are combined into one log file.
    SUBMISSION_OUTPUT="$(
        sbatch \
            --output="${LOG_FILE}" \
            --error="${LOG_FILE}" \
            --open-mode=truncate \
            "$0" \
            --run-analysis \
            "${FIRST_CSV}" \
            "${SECOND_CSV}" \
            "${OVERLAP_CSV}" \
            "${FIRST_PREFIX}" \
            "${SECOND_PREFIX}" \
            "${OUTPUT_PNG}" \
            "${OUTPUT_MEMBERSHIP}" \
            "${OUTPUT_SUMMARY}"
    )"

    echo "${SUBMISSION_OUTPUT}"
    echo
    echo "[INFO] Venn diagram job submitted."
    echo "[INFO] Follow the log with:"
    echo
    echo "tail -f \"${LOG_FILE}\""
}


# =============================================================================
# Venn diagram analysis
# =============================================================================


# ==============================================================================
# FUNCTION: run_analysis
# ==============================================================================
#
# Purpose:
#   Run Venn membership analysis and plotting inside the submitted SLURM job.
#
# Required arguments:
#
#   $1  First source POI CSV.
#   $2  Second source POI CSV.
#   $3  Overlap CSV.
#   $4  First source prefix.
#   $5  Second source prefix.
#   $6  Output PNG.
#   $7  Output membership CSV.
#   $8  Output summary CSV.
#
run_analysis() {
    if [[ $# -ne 8 ]]; then
        echo "[ERROR] Internal analysis mode requires eight arguments." >&2
        exit 1
    fi

    FIRST_CSV="$1"
    SECOND_CSV="$2"
    OVERLAP_CSV="$3"
    FIRST_PREFIX="$4"
    SECOND_PREFIX="$5"
    OUTPUT_PNG="$6"
    OUTPUT_MEMBERSHIP="$7"
    OUTPUT_SUMMARY="$8"

    # Validate all required input files.
    for required_file in \
        "${FIRST_CSV}" \
        "${SECOND_CSV}" \
        "${OVERLAP_CSV}"
    do
        if [[ ! -f "${required_file}" ]]; then
            echo "[ERROR] Required CSV file does not exist:" >&2
            echo "        ${required_file}" >&2
            exit 1
        fi
    done

    # Create output directories when needed.
    mkdir -p "${CSV_DIR}" "${VENN_DIR}"

    # Prepare Python and required packages.
    prepare_python_environment

    # Export all values required by the quoted Python here-document.
    export FIRST_CSV
    export SECOND_CSV
    export OVERLAP_CSV
    export FIRST_PREFIX
    export SECOND_PREFIX
    export OUTPUT_PNG
    export OUTPUT_MEMBERSHIP
    export OUTPUT_SUMMARY

    echo
    echo "============================================================"
    echo "Starting POI Venn analysis"
    echo "============================================================"
    echo "SLURM job ID:       ${SLURM_JOB_ID:-not available}"
    echo "First POI CSV:      ${FIRST_CSV}"
    echo "Second POI CSV:     ${SECOND_CSV}"
    echo "Overlap CSV:        ${OVERLAP_CSV}"
    echo "Output PNG:         ${OUTPUT_PNG}"
    echo "Membership CSV:     ${OUTPUT_MEMBERSHIP}"
    echo "Summary CSV:        ${OUTPUT_SUMMARY}"
    echo "============================================================"

    # --------------------------------------------------------------------------
    # Embedded Python analysis
    # --------------------------------------------------------------------------
    #
    # The quoted PYTHON delimiter prevents Bash from interpreting the Python
    # code. Configuration is read through environment variables.
    #
    "${PYTHON_CMD}" <<'PYTHON'
"""
Create a POI Venn diagram and detailed membership tables.

The analysis reads two original POI CSV files and the overlap CSV generated
from those same source files. It maps each overlap coordinate back to a unique
source row, validates count consistency, creates membership and summary tables,
and renders a clean Venn-style figure.
"""

import os
import re
import sys
from pathlib import Path

import matplotlib

# Required for Matplotlib on a noninteractive compute node.
matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import numpy as np
import pandas as pd


# =============================================================================
# Configuration supplied by the Bash wrapper
# =============================================================================

FIRST_PATH = Path(
    os.environ["FIRST_CSV"]
)

SECOND_PATH = Path(
    os.environ["SECOND_CSV"]
)

OVERLAP_PATH = Path(
    os.environ["OVERLAP_CSV"]
)

FIRST_PREFIX = os.environ[
    "FIRST_PREFIX"
]

SECOND_PREFIX = os.environ[
    "SECOND_PREFIX"
]

OUTPUT_PNG = Path(
    os.environ["OUTPUT_PNG"]
)

OUTPUT_MEMBERSHIP = Path(
    os.environ["OUTPUT_MEMBERSHIP"]
)

OUTPUT_SUMMARY = Path(
    os.environ["OUTPUT_SUMMARY"]
)


def create_short_dataset_label(
    prefix: str,
) -> str:
    """
    Create a short readable dataset label for the Venn diagram.

    Known project-specific filename patterns are reduced to concise labels.
    Unknown names are cleaned by removing common workflow suffixes.

    Examples
    --------
    MQNFGR_3_mitosis_WT_020.sorted.indexed.BrdU.detect_top20_poi
        becomes:
    MQNFGR_3_WT

    MQNFGR_4_mitosis_MMS_020.sorted.indexed.BrdU.detect_top20_poi
        becomes:
    MQNFGR_4_MMS

    MQNFGR_1_negative_control_020.sorted.indexed.BrdU.detect_top20_poi
        becomes:
    MQNFGR_1_negative_control

    M5PWTM_1_1_mitosis_016.sorted.indexed.BrdU.detect_top20_poi
        becomes:
    M5PWTM_1_1_mitosis

    BrdU_pct_sorted_desc_10kb_20
        becomes:
    BrdU_pct_10kb_20
    """
    filename = Path(prefix).name

    known_patterns = [
        (
            r"^(MQNFGR_\d+)_mitosis_(WT|MMS)(?:_\d+)?",
            lambda match: (
                f"{match.group(1)}_{match.group(2)}"
            ),
        ),
        (
            r"^(MQNFGR_\d+)_negative_control(?:_\d+)?",
            lambda match: (
                f"{match.group(1)}_negative_control"
            ),
        ),
        (
            r"^(MQNFGR_\d+)_positive_control(?:_\d+)?",
            lambda match: (
                f"{match.group(1)}_positive_control"
            ),
        ),
        (
            r"^(MQNFGR_\d+)_s_phase(?:_\d+)?",
            lambda match: (
                f"{match.group(1)}_S_phase"
            ),
        ),
        (
            r"^(M5PWTM_\d+_\d+)_mitosis(?:_\d+)?",
            lambda match: (
                f"{match.group(1)}_mitosis"
            ),
        ),
        (
            r"^BrdU_pct_sorted_desc_10kb_(\d+)",
            lambda match: (
                f"BrdU_pct_10kb_{match.group(1)}"
            ),
        ),
        (
            r"^BrdU_pct_sorted_desc_10kb",
            lambda match: "BrdU_pct_10kb",
        ),
    ]

    for pattern, formatter in known_patterns:
        match = re.search(
            pattern,
            filename,
            flags=re.IGNORECASE,
        )

        if match:
            return formatter(match)

    # General fallback for unknown filenames.
    shortened = filename

    suffix_patterns = [
        r"\.sorted.*$",
        r"_sorted.*$",
        r"\.indexed.*$",
        r"_indexed.*$",
        r"\.BrdU.*$",
        r"_BrdU.*$",
        r"_top20_poi.*$",
        r"\.top20_poi.*$",
    ]

    for suffix_pattern in suffix_patterns:
        shortened = re.sub(
            suffix_pattern,
            "",
            shortened,
            flags=re.IGNORECASE,
        )

    # Prevent extremely long labels.
    if len(shortened) > 35:
        shortened = (
            shortened[:32]
            + "..."
        )

    return shortened


# Generate concise labels used in the figure and output CSV files.
FIRST_LABEL = create_short_dataset_label(
    FIRST_PREFIX
)

SECOND_LABEL = create_short_dataset_label(
    SECOND_PREFIX
)

print(
    f"[INFO] First diagram label:  "
    f"{FIRST_LABEL}"
)

print(
    f"[INFO] Second diagram label: "
    f"{SECOND_LABEL}"
)


def normalize_chromosome(
    value: object,
) -> str:
    """
    Normalize chromosome values to stable string labels.

    Examples
    --------
    1.0 becomes 1
    15 becomes 15
    MT remains MT
    """
    value_string = str(
        value
    ).strip()

    if value_string.endswith(".0"):
        possible_integer = (
            value_string[:-2]
        )

        if possible_integer.isdigit():
            return possible_integer

    return value_string


def read_source_csv(
    path: Path,
    dataset_name: str,
) -> pd.DataFrame:
    """
    Read and validate one original POI CSV.

    Required columns
    ----------------
    chrom
    start
    end

    Representative position
    -----------------------
    If a position column exists, it is converted to numeric form. Otherwise,
    start is used as the representative position.

    Internal source-row IDs
    -----------------------
    A unique _source_row_id is assigned after validation. These IDs allow
    overlap rows to be mapped back to source records without relying only on
    DataFrame indices.

    Parameters
    ----------
    path
        Source POI CSV path.

    dataset_name
        Human-readable label used in status and error messages.

    Returns
    -------
    pandas.DataFrame
        Validated source POI rows.
    """
    print(
        f"[INFO] Reading {dataset_name}:"
    )

    print(
        f"       {path}"
    )

    dataframe = pd.read_csv(
        path
    )

    required_columns = {
        "chrom",
        "start",
        "end",
    }

    missing_columns = (
        required_columns.difference(
            dataframe.columns
        )
    )

    if missing_columns:
        raise ValueError(
            f"{dataset_name} is missing required columns: "
            f"{', '.join(sorted(missing_columns))}"
        )

    dataframe = dataframe.copy()

    dataframe["chrom"] = (
        dataframe["chrom"].map(
            normalize_chromosome
        )
    )

    dataframe["start"] = (
        pd.to_numeric(
            dataframe["start"],
            errors="coerce",
        )
    )

    dataframe["end"] = (
        pd.to_numeric(
            dataframe["end"],
            errors="coerce",
        )
    )

    if "position" in dataframe.columns:
        dataframe["position"] = (
            pd.to_numeric(
                dataframe["position"],
                errors="coerce",
            )
        )
    else:
        dataframe["position"] = (
            dataframe["start"]
        )

    original_row_count = len(
        dataframe
    )

    dataframe = dataframe.dropna(
        subset=[
            "chrom",
            "start",
            "end",
            "position",
        ]
    ).copy()

    dataframe = dataframe[
        (dataframe["start"] >= 0)
        & (
            dataframe["end"]
            > dataframe["start"]
        )
        & (
            dataframe["position"]
            >= 0
        )
    ].copy()

    removed_row_count = (
        original_row_count
        - len(dataframe)
    )

    if removed_row_count:
        print(
            f"[WARNING] Removed {removed_row_count} invalid rows "
            f"from {dataset_name}.",
            file=sys.stderr,
        )

    dataframe["start"] = (
        dataframe["start"].astype(
            np.int64
        )
    )

    dataframe["end"] = (
        dataframe["end"].astype(
            np.int64
        )
    )

    dataframe["position"] = (
        dataframe["position"].astype(
            np.int64
        )
    )

    # Generate ranks when the source CSV does not contain them.
    if "rank" not in dataframe.columns:
        dataframe.insert(
            0,
            "rank",
            range(
                1,
                len(dataframe) + 1,
            ),
        )
    else:
        dataframe["rank"] = (
            pd.to_numeric(
                dataframe["rank"],
                errors="coerce",
            )
        )

    dataframe = dataframe.reset_index(
        drop=True
    )

    # Stable internal row identifier used for overlap membership mapping.
    dataframe["_source_row_id"] = (
        np.arange(
            len(dataframe),
            dtype=np.int64,
        )
    )

    print(
        f"[INFO] Valid rows: "
        f"{len(dataframe)}"
    )

    return dataframe


def read_overlap_csv(
    path: Path,
) -> pd.DataFrame:
    """
    Read and validate the overlap CSV generated by the POI comparison workflow.

    Required columns
    ----------------
    chrom
    first_start
    first_end
    first_position
    second_start
    second_end
    second_position
    distance_bp

    Parameters
    ----------
    path
        Overlap CSV path.

    Returns
    -------
    pandas.DataFrame
        Validated overlap pairs.
    """
    print(
        "[INFO] Reading overlap CSV:"
    )

    print(
        f"       {path}"
    )

    dataframe = pd.read_csv(
        path
    )

    required_columns = {
        "chrom",
        "first_start",
        "first_end",
        "first_position",
        "second_start",
        "second_end",
        "second_position",
        "distance_bp",
    }

    missing_columns = (
        required_columns.difference(
            dataframe.columns
        )
    )

    if missing_columns:
        raise ValueError(
            "Overlap CSV is missing required columns: "
            f"{', '.join(sorted(missing_columns))}"
        )

    dataframe = dataframe.copy()

    dataframe["chrom"] = (
        dataframe["chrom"].map(
            normalize_chromosome
        )
    )

    numeric_columns = [
        "first_start",
        "first_end",
        "first_position",
        "second_start",
        "second_end",
        "second_position",
        "distance_bp",
    ]

    for column in numeric_columns:
        dataframe[column] = (
            pd.to_numeric(
                dataframe[column],
                errors="coerce",
            )
        )

    original_row_count = len(
        dataframe
    )

    dataframe = dataframe.dropna(
        subset=[
            "chrom",
            *numeric_columns,
        ]
    ).copy()

    removed_row_count = (
        original_row_count
        - len(dataframe)
    )

    if removed_row_count:
        print(
            f"[WARNING] Removed {removed_row_count} invalid overlap rows.",
            file=sys.stderr,
        )

    for column in numeric_columns:
        dataframe[column] = (
            dataframe[column].astype(
                np.int64
            )
        )

    if "overlap_id" not in dataframe.columns:
        dataframe.insert(
            0,
            "overlap_id",
            range(
                1,
                len(dataframe) + 1,
            ),
        )

    dataframe = dataframe.reset_index(
        drop=True
    )

    print(
        f"[INFO] Valid overlap pairs: "
        f"{len(dataframe)}"
    )

    return dataframe


def coordinate_key(
    chromosome: object,
    start: object,
    end: object,
) -> tuple[str, int, int]:
    """
    Return an exact normalized chromosome/start/end coordinate key.
    """
    return (
        normalize_chromosome(
            chromosome
        ),
        int(start),
        int(end),
    )


def map_overlap_rows_to_source(
    source_dataframe: pd.DataFrame,
    overlap_dataframe: pd.DataFrame,
    side: str,
) -> tuple[set[int], list[int]]:
    """
    Map overlap coordinates back to one original source POI dataset.

    Parameters
    ----------
    source_dataframe
        Validated original POI table.

    overlap_dataframe
        Validated overlap-pair table.

    side
        ``first`` uses first_start and first_end.

        ``second`` uses second_start and second_end.

    Duplicate-coordinate behavior
    -----------------------------
    When a source dataset contains duplicate exact coordinates, unused source
    IDs are assigned one at a time. This prevents one source row from being
    counted repeatedly.

    Returns
    -------
    tuple[set[int], list[int]]
        Set of matched source-row IDs and list of overlap IDs that could not be
        mapped.
    """
    coordinate_to_source_ids: dict[
        tuple[str, int, int],
        list[int],
    ] = {}

    # Build a lookup from exact coordinates to one or more source-row IDs.
    for _, source_row in source_dataframe.iterrows():
        key = coordinate_key(
            source_row["chrom"],
            source_row["start"],
            source_row["end"],
        )

        coordinate_to_source_ids.setdefault(
            key,
            [],
        ).append(
            int(
                source_row[
                    "_source_row_id"
                ]
            )
        )

    used_source_ids: set[int] = set()
    missing_overlap_ids: list[int] = []

    overlap_start_column = (
        f"{side}_start"
    )

    overlap_end_column = (
        f"{side}_end"
    )

    for _, overlap_row in overlap_dataframe.iterrows():
        key = coordinate_key(
            overlap_row["chrom"],
            overlap_row[
                overlap_start_column
            ],
            overlap_row[
                overlap_end_column
            ],
        )

        candidate_source_ids = (
            coordinate_to_source_ids.get(
                key,
                [],
            )
        )

        selected_source_id = None

        # Use the first source row at this coordinate that has not already been
        # assigned to another overlap pair.
        for source_id in candidate_source_ids:
            if source_id not in used_source_ids:
                selected_source_id = (
                    source_id
                )
                break

        if selected_source_id is None:
            missing_overlap_ids.append(
                int(
                    overlap_row[
                        "overlap_id"
                    ]
                )
            )
        else:
            used_source_ids.add(
                selected_source_id
            )

    return (
        used_source_ids,
        missing_overlap_ids,
    )


def copy_optional_columns(
    destination_row: dict,
    source_row: pd.Series,
    prefix: str,
) -> None:
    """
    Copy optional BrdU and coverage values into a membership output row.

    Missing columns are stored as NaN so the membership CSV has a consistent
    combined schema.
    """
    optional_columns = [
        "BrdU_pct",
        "frac_mod",
        "BrdU_count",
        "Nmod",
        "combined_Nmod",
        "combined_Nvalid_cov",
        "positive_Nmod",
        "positive_Nvalid_cov",
        "negative_Nmod",
        "negative_Nvalid_cov",
    ]

    for column in optional_columns:
        destination_row[
            f"{prefix}_{column}"
        ] = source_row.get(
            column,
            np.nan,
        )


# =============================================================================
# Read source and overlap CSV files
# =============================================================================

first_dataframe = read_source_csv(
    FIRST_PATH,
    "first POI dataset",
)

second_dataframe = read_source_csv(
    SECOND_PATH,
    "second POI dataset",
)

overlap_dataframe = read_overlap_csv(
    OVERLAP_PATH,
)


# =============================================================================
# Map overlap rows back to exact source coordinates
# =============================================================================

matched_first_ids, missing_first_ids = (
    map_overlap_rows_to_source(
        source_dataframe=first_dataframe,
        overlap_dataframe=overlap_dataframe,
        side="first",
    )
)

matched_second_ids, missing_second_ids = (
    map_overlap_rows_to_source(
        source_dataframe=second_dataframe,
        overlap_dataframe=overlap_dataframe,
        side="second",
    )
)

if missing_first_ids:
    print(
        "[ERROR] These overlap IDs could not be found in the first CSV:",
        file=sys.stderr,
    )

    print(
        "        "
        + ", ".join(
            map(
                str,
                missing_first_ids,
            )
        ),
        file=sys.stderr,
    )

if missing_second_ids:
    print(
        "[ERROR] These overlap IDs could not be found in the second CSV:",
        file=sys.stderr,
    )

    print(
        "        "
        + ", ".join(
            map(
                str,
                missing_second_ids,
            )
        ),
        file=sys.stderr,
    )

# Stop when the overlap CSV does not correspond to the selected source files.
if missing_first_ids or missing_second_ids:
    raise ValueError(
        "The overlap CSV does not correspond to the selected original "
        "POI CSV files. Select the same two source files that were used "
        "to create the overlap CSV."
    )

overlap_count = len(
    overlap_dataframe
)

# Confirm one source row was found for every overlap on both sides.
if len(matched_first_ids) != overlap_count:
    raise ValueError(
        "The number of first-dataset matches differs from the overlap count."
    )

if len(matched_second_ids) != overlap_count:
    raise ValueError(
        "The number of second-dataset matches differs from the overlap count."
    )


# =============================================================================
# Identify unique POIs from each source dataset
# =============================================================================

first_unique_dataframe = first_dataframe[
    ~first_dataframe[
        "_source_row_id"
    ].isin(
        matched_first_ids
    )
].copy()

second_unique_dataframe = second_dataframe[
    ~second_dataframe[
        "_source_row_id"
    ].isin(
        matched_second_ids
    )
].copy()

first_total = len(
    first_dataframe
)

second_total = len(
    second_dataframe
)

first_unique_count = len(
    first_unique_dataframe
)

second_unique_count = len(
    second_unique_dataframe
)


# =============================================================================
# Print and validate Venn-region counts
# =============================================================================

print()
print("============================================================")
print("Venn diagram counts")
print("============================================================")
print(f"First dataset label:       {FIRST_LABEL}")
print(f"Second dataset label:      {SECOND_LABEL}")
print(f"First dataset total:       {first_total}")
print(f"Unique to first dataset:   {first_unique_count}")
print(f"Overlapping pairs:         {overlap_count}")
print(f"Unique to second dataset:  {second_unique_count}")
print(f"Second dataset total:      {second_total}")
print("============================================================")

if (
    first_unique_count
    + overlap_count
    != first_total
):
    raise ValueError(
        "The first Venn counts do not add up to the first dataset total."
    )

if (
    second_unique_count
    + overlap_count
    != second_total
):
    raise ValueError(
        "The second Venn counts do not add up to the second dataset total."
    )


# =============================================================================
# Build one CSV containing every Venn region
# =============================================================================

membership_rows: list[dict] = []


# -----------------------------------------------------------------------------
# Unique POIs from the first dataset
# -----------------------------------------------------------------------------

for _, source_row in first_unique_dataframe.iterrows():
    output_row = {
        "membership": "unique_to_first",
        "first_dataset": FIRST_PREFIX,
        "first_dataset_label": FIRST_LABEL,
        "second_dataset": SECOND_PREFIX,
        "second_dataset_label": SECOND_LABEL,
        "chrom": source_row["chrom"],
        "first_rank": source_row.get(
            "rank",
            np.nan,
        ),
        "first_start": source_row[
            "start"
        ],
        "first_end": source_row[
            "end"
        ],
        "first_position": source_row[
            "position"
        ],
        "second_rank": np.nan,
        "second_start": np.nan,
        "second_end": np.nan,
        "second_position": np.nan,
        "distance_bp": np.nan,
    }

    copy_optional_columns(
        destination_row=output_row,
        source_row=source_row,
        prefix="first",
    )

    membership_rows.append(
        output_row
    )


# -----------------------------------------------------------------------------
# Overlapping POI pairs
# -----------------------------------------------------------------------------

for _, overlap_row in overlap_dataframe.iterrows():
    output_row = {
        "membership": "overlap",
        "first_dataset": FIRST_PREFIX,
        "first_dataset_label": FIRST_LABEL,
        "second_dataset": SECOND_PREFIX,
        "second_dataset_label": SECOND_LABEL,
        "chrom": overlap_row["chrom"],
        "first_rank": overlap_row.get(
            "first_rank",
            np.nan,
        ),
        "first_start": overlap_row[
            "first_start"
        ],
        "first_end": overlap_row[
            "first_end"
        ],
        "first_position": overlap_row[
            "first_position"
        ],
        "second_rank": overlap_row.get(
            "second_rank",
            np.nan,
        ),
        "second_start": overlap_row[
            "second_start"
        ],
        "second_end": overlap_row[
            "second_end"
        ],
        "second_position": overlap_row[
            "second_position"
        ],
        "distance_bp": overlap_row[
            "distance_bp"
        ],
    }

    # Preserve extra columns already present in the overlap CSV.
    for column in overlap_dataframe.columns:
        if column in output_row:
            continue

        # Internal source indices are not included in the membership output.
        if column in {
            "first_index",
            "second_index",
        }:
            continue

        output_row[column] = (
            overlap_row.get(
                column,
                np.nan,
            )
        )

    membership_rows.append(
        output_row
    )


# -----------------------------------------------------------------------------
# Unique POIs from the second dataset
# -----------------------------------------------------------------------------

for _, source_row in second_unique_dataframe.iterrows():
    output_row = {
        "membership": "unique_to_second",
        "first_dataset": FIRST_PREFIX,
        "first_dataset_label": FIRST_LABEL,
        "second_dataset": SECOND_PREFIX,
        "second_dataset_label": SECOND_LABEL,
        "chrom": source_row["chrom"],
        "first_rank": np.nan,
        "first_start": np.nan,
        "first_end": np.nan,
        "first_position": np.nan,
        "second_rank": source_row.get(
            "rank",
            np.nan,
        ),
        "second_start": source_row[
            "start"
        ],
        "second_end": source_row[
            "end"
        ],
        "second_position": source_row[
            "position"
        ],
        "distance_bp": np.nan,
    }

    copy_optional_columns(
        destination_row=output_row,
        source_row=source_row,
        prefix="second",
    )

    membership_rows.append(
        output_row
    )


# =============================================================================
# Sort and write the membership CSV
# =============================================================================

membership_dataframe = pd.DataFrame(
    membership_rows
)

membership_sort_order = {
    "unique_to_first": 0,
    "overlap": 1,
    "unique_to_second": 2,
}

membership_dataframe[
    "_membership_order"
] = (
    membership_dataframe[
        "membership"
    ]
    .map(
        membership_sort_order
    )
    .fillna(99)
)

# Numeric chromosomes are sorted before nonnumeric labels such as MT.
membership_dataframe[
    "_numeric_chrom"
] = pd.to_numeric(
    membership_dataframe[
        "chrom"
    ],
    errors="coerce",
)

membership_dataframe[
    "_text_chrom"
] = (
    membership_dataframe[
        "_numeric_chrom"
    ]
    .isna()
    .astype(int)
)

membership_dataframe = (
    membership_dataframe.sort_values(
        by=[
            "_membership_order",
            "_text_chrom",
            "_numeric_chrom",
            "chrom",
            "first_position",
            "second_position",
        ],
        kind="mergesort",
        na_position="last",
    )
)

membership_dataframe = (
    membership_dataframe.drop(
        columns=[
            "_membership_order",
            "_numeric_chrom",
            "_text_chrom",
        ]
    )
)

OUTPUT_MEMBERSHIP.parent.mkdir(
    parents=True,
    exist_ok=True,
)

membership_dataframe.to_csv(
    OUTPUT_MEMBERSHIP,
    index=False,
)


# =============================================================================
# Create summary CSV
# =============================================================================

first_overlap_percentage = (
    (
        overlap_count
        / first_total
    )
    * 100
    if first_total
    else 0.0
)

second_overlap_percentage = (
    (
        overlap_count
        / second_total
    )
    * 100
    if second_total
    else 0.0
)

summary_dataframe = pd.DataFrame(
    [
        {
            "first_dataset": FIRST_PREFIX,
            "first_dataset_label": FIRST_LABEL,
            "second_dataset": SECOND_PREFIX,
            "second_dataset_label": SECOND_LABEL,
            "first_total_pois": first_total,
            "unique_to_first": first_unique_count,
            "overlap_pairs": overlap_count,
            "unique_to_second": second_unique_count,
            "second_total_pois": second_total,
            "first_overlap_pct": first_overlap_percentage,
            "second_overlap_pct": second_overlap_percentage,
        }
    ]
)

summary_dataframe.to_csv(
    OUTPUT_SUMMARY,
    index=False,
)


# =============================================================================
# Create clean Venn-style Matplotlib figure
# =============================================================================

figure, axis = plt.subplots(
    figsize=(
        12,
        8,
    )
)

# Draw the left dataset circle.
left_circle = Circle(
    (
        0.42,
        0.50,
    ),
    0.25,
    fill=False,
    linewidth=3,
)

# Draw the right dataset circle.
right_circle = Circle(
    (
        0.58,
        0.50,
    ),
    0.25,
    fill=False,
    linewidth=3,
)

axis.add_patch(
    left_circle
)

axis.add_patch(
    right_circle
)

# Short readable dataset labels.
axis.text(
    0.29,
    0.81,
    FIRST_LABEL,
    ha="center",
    va="center",
    fontsize=18,
    fontweight="bold",
)

axis.text(
    0.71,
    0.81,
    SECOND_LABEL,
    ha="center",
    va="center",
    fontsize=18,
    fontweight="bold",
)

# Venn-region counts.
axis.text(
    0.30,
    0.50,
    str(
        first_unique_count
    ),
    ha="center",
    va="center",
    fontsize=40,
    fontweight="bold",
)

axis.text(
    0.50,
    0.50,
    str(
        overlap_count
    ),
    ha="center",
    va="center",
    fontsize=40,
    fontweight="bold",
)

axis.text(
    0.70,
    0.50,
    str(
        second_unique_count
    ),
    ha="center",
    va="center",
    fontsize=40,
    fontweight="bold",
)

# Region descriptions.
axis.text(
    0.30,
    0.40,
    "Unique",
    ha="center",
    va="center",
    fontsize=13,
)

axis.text(
    0.50,
    0.40,
    "Overlap",
    ha="center",
    va="center",
    fontsize=13,
)

axis.text(
    0.70,
    0.40,
    "Unique",
    ha="center",
    va="center",
    fontsize=13,
)

axis.set_title(
    "Top POI overlap",
    fontsize=22,
    fontweight="bold",
    pad=20,
)

# Short readable footer.
axis.text(
    0.50,
    0.13,
    (
        f"{FIRST_LABEL}: {first_total} total POIs   |   "
        f"{overlap_count} overlapping pairs   |   "
        f"{SECOND_LABEL}: {second_total} total POIs"
    ),
    ha="center",
    va="center",
    fontsize=12,
)

axis.set_xlim(
    0.05,
    0.95,
)

axis.set_ylim(
    0.05,
    0.90,
)

axis.set_aspect(
    "equal"
)

axis.axis(
    "off"
)

OUTPUT_PNG.parent.mkdir(
    parents=True,
    exist_ok=True,
)

plt.savefig(
    OUTPUT_PNG,
    dpi=300,
    bbox_inches="tight",
)

plt.close(
    figure
)


# =============================================================================
# Report successful completion
# =============================================================================

print()
print("============================================================")
print("POI Venn analysis completed successfully")
print("============================================================")
print("Venn diagram:")
print(f"  {OUTPUT_PNG}")
print()
print("Combined membership CSV:")
print(f"  {OUTPUT_MEMBERSHIP}")
print()
print("Summary CSV:")
print(f"  {OUTPUT_SUMMARY}")
print("============================================================")
PYTHON
}


# =============================================================================
# Main
# =============================================================================
#
# --run-analysis:
#   Execute the internal SLURM analysis stage.
#
# Any other invocation:
#   Enter interactive file selection and submission mode.
#

if [[ "${1:-}" == "--run-analysis" ]]; then
    shift
    run_analysis "$@"
else
    submit_interactive_job
fi